### PR TITLE
OpenCV 4.2.0

### PR DESCRIPTION
**Pull request by afraz-ahmed**
For INC1031023

* [x] Assigned to reviewer

OpenCV-4.2.0-foss-2019b-Python-3.7.4.eb
* [ ] EL7-cascadelake
* [ ] EL7-haswell
* [ ] Ubuntu16 VM

OpenCV-4.2.0-fosscuda-2019b-Python-3.7.4.eb
* [ ] EL7-haswell
* [ ] EL7-power9

Rebuild in order:
* [ ] HarfBuzz 2.6.4-GCCcore-8.3.0
* [ ] Pango 1.44.7-GCCcore-8.3.0
* [ ] gnuplot 5.2.8-GCCcore-8.3.0
* [ ] canu 1.9-GCCcore-8.3.0-Perl-5.30.0

### CODE REVIEW

**Comment by afraz-ahmed** [comment]
I can't find where the ICU dependency is that is causing the tests to fail. There are two versions of ICC on GCCcore-8.3.0, but wouldn't all of the easyconfigs specify which version to use?

**Comment by edmondac** [comment]
https://github.com/bear-rsg/easybuild-easyconfigs/blob/OpenCV/easybuild/easyconfigs/i/ICU/ICU-64.2-GCCcore-8.3.0.eb is for Python 2

https://github.com/bear-rsg/easybuild-easyconfigs/blob/OpenCV/easybuild/easyconfigs/i/ICU/ICU-65.1-GCCcore-8.3.0.eb is for Python 3

The easiest solution might be to add an exception here: https://github.com/bear-rsg/easybuild-easyconfigs/blob/OpenCV/test/easyconfigs/easyconfigs.py#L157

@branfosj opinion?

**Comment by branfosj** [comment]
We seem to have inherited these ecs from upstream and they later fixed the issue. There are two choices:
1. Change anything that uses 65.1 to use 64.1 and rebuild. (64.1 is used by R, so we're not changing that!) 65.1 is used directly by HarfBuzz/2.6.4-GCCcore-8.3.0 and then onwards by  Pango/1.44.7-GCCcore-8.3.0, gnuplot/5.2.8-GCCcore-8.3.0, and canu/1.9-GCCcore-8.3.0-Perl-5.30.0
2. Live with it and allow it in the tests by adding to the `old_dep_versions` section

We are seeing the issue here due to GTK+ having a Pango dep.

**Comment by edmondac** [comment]
`HarfBuzz-2.6.4-GCCcore-8.3.0.eb` is the only thing using `ICU-65.1-GCCcore-8.3.0.eb` - so let's switch it to 64.2 and make ICU 64.2 support both Python versions.

**Comment by edmondac** [comment]
> `HarfBuzz-2.6.4-GCCcore-8.3.0.eb` is the only thing using `ICU-65.1-GCCcore-8.3.0.eb` - so let's switch it to 64.2 and make ICU 64.2 support both Python versions.

Then we'd need to rebuild:

- HarfBuzz 2.6.4-GCCcore-8.3.0
- Pango 1.44.7-GCCcore-8.3.0
- gnuplot 5.2.8-GCCcore-8.3.0
- canu 1.9-GCCcore-8.3.0-Perl-5.30.0

**Comment by branfosj** [comment]
ICU is using Python as a build dep, so it does not matter which version it uses. We can just update HarfBuzz and do the rebuild.

**Comment by edmondac** [comment]
Note, `canu/1.9-GCCcore-8.3.0-Perl-5.30.0` doesn't exist on POWER9, so not rebuilding it.

**Comment by edmondac** [comment]
On POWER9 GdkPixbuf fails like this:
```
[27/173] Compiling C object 'gdk-pixbuf/pixops/a255f19@@timescale@exe/timescale.c.o'.
[28/173] Generating gdk-pixbuf-enum-types.h with a meson_exe.py custom command.
[29/173] Compiling C object 'gdk-pixbuf/pixops/a255f19@@pixops@sta/pixops.c.o'.
ninja: build stopped: subcommand failed.
 (at easybuild/2019b/src/easybuild-framework/easybuild/tools/run.py:529 in parse_cmd_output)
== 2020-05-01 15:24:14,457 easyblock.py:3094 WARNING build failed (first 300 chars): cmd " ninja -j 36 " exited with exit code 1 and output:
[1/173] Generating gdk-pixbuf-csource-man with a custom command.
FAILED: docs/gdk-pixbuf-csource.1 
/bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringpa
== 2020-05-01 15:24:14,457 easyblock.py:295 INFO Closing log for application name Gdk-Pixbuf version 2.38.2
```

**Comment by edmondac** [comment]
> On POWER9 GdkPixbuf fails like this:
> 
> ```
> [27/173] Compiling C object 'gdk-pixbuf/pixops/a255f19@@timescale@exe/timescale.c.o'.
> [28/173] Generating gdk-pixbuf-enum-types.h with a meson_exe.py custom command.
> [29/173] Compiling C object 'gdk-pixbuf/pixops/a255f19@@pixops@sta/pixops.c.o'.
> ninja: build stopped: subcommand failed.
>  (at easybuild/2019b/src/easybuild-framework/easybuild/tools/run.py:529 in parse_cmd_output)
> == 2020-05-01 15:24:14,457 easyblock.py:3094 WARNING build failed (first 300 chars): cmd " ninja -j 36 " exited with exit code 1 and output:
> [1/173] Generating gdk-pixbuf-csource-man with a custom command.
> FAILED: docs/gdk-pixbuf-csource.1 
> /bin/xsltproc --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringpa
> == 2020-05-01 15:24:14,457 easyblock.py:295 INFO Closing log for application name Gdk-Pixbuf version 2.38.2
> ```

If we need this on POWER9 then please investigate @afraz-ahmed - but if the user didn't mention it then you can ignore it for now.

**Comment by afraz-ahmed** [comment]
The user didn't mention Power9, so will leave it.

**Pull request merged**
