### PR TITLE
{tools}[system/system] VSCode v2.1698

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

For OnDemand

`VSCode-2.1698.eb`
* [x] Assigned to reviewer
* [ ] EL7-cascadelake
* [ ] EL7-haswell
* [ ] EL7-sandybridge

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/8356fdda4b39a788089a1b123be14137 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/9a671fcb69f232d7490ae031cbe1f39c for a full test report.

**Comment by orbsmiv** [comment]
Built on all requested platforms

**Comment by orbsmiv** [comment]
https://bear-apps.bham.ac.uk/applications/VSCode/2.1698/

**Pull request merged**
