### PR TITLE
ABAQUS-2020 easyconfig -- for discussion only

### PR DESCRIPTION
**Pull request by afraz-ahmed**
For INC1019561

Requires https://github.com/bear-rsg/easybuild-easyblocks/pull/21

`ABAQUS-2020.eb`
* [x] Assigned to reviewer
* [ ] EL7-cascadelake
* [ ] EL7-haswell
* [ ] Ubuntu16 VM

### CODE REVIEW

**Comment by edmondac** [comment]
Fails on Ubuntu - presumably because it's calling `sh` instead of `bash`:
```
== 2020-04-21 11:07:18,669 easyblock.py:2848 INFO Running method install_step part of step install
== 2020-04-21 11:07:20,116 build_log.py:164 ERROR EasyBuild crashed with an error (at easybuild/2019b/src/easybuild-framework/easybuild/base/exceptions.py:124 in __init__): cmd "./StartTUI.sh" exited with exit code 8 and output:
./StartTUI.sh: 4: ./StartTUI.sh: typeset: not found
CurrentMediaDir initial=""
./StartTUI.sh: 6: ./StartTUI.sh: typeset: not found
./StartTUI.sh: 8: ./StartTUI.sh: [[: not found
./StartTUI.sh: 10: ./StartTUI.sh: [[: not found
CurrentMediaDir="/dev/shm/build-edmondac-admin/edmondac-admin-2019b/ABAQUS/2020/system-system/AM_SIM_Abaqus_Extend.AllOS/1/"
./StartTUI.sh: 18: ./StartTUI.sh: typeset: not found
./StartTUI.sh: 6: /dev/shm/build-edmondac-admin/edmondac-admin-2019b/ABAQUS/2020/system-system/AM_SIM_Abaqus_Extend.AllOS/1//inst/common/get_DSY_OS.sh: [[: not found
Current operating system: "Linux"
./StartTUI.sh: 18: /dev/shm/build-edmondac-admin/edmondac-admin-2019b/ABAQUS/2020/system-system/AM_SIM_Abaqus_Extend.AllOS/1//inst/common/get_DSY_OS.sh: [[: not found
./StartTUI.sh: 26: /dev/shm/build-edmondac-admin/edmondac-admin-2019b/ABAQUS/2020/system-system/AM_SIM_Abaqus_Extend.AllOS/1//inst/common/get_DSY_OS.sh: [[: not found
/usr/bin/lsb_release
./StartTUI.sh: 4: /dev/shm/build-edmondac-admin/edmondac-admin-2019b/ABAQUS/2020/system-system/AM_SIM_Abaqus_Extend.AllOS/1//inst/common/init/Linux.sh: [[: not found
DSY_OS_Release="Ubuntu"
./StartTUI.sh: 13: /dev/shm/build-edmondac-admin/edmondac-admin-2019b/ABAQUS/2020/system-system/AM_SIM_Abaqus_Extend.AllOS/1//inst/common/init/Linux.sh: [[: not found
Unknown linux release "Ubuntu"
exit 8
 (at easybuild/2019b/src/easybuild-framework/easybuild/tools/run.py:529 in parse_cmd_output)
```

**Comment by edmondac** [comment]
Failed on haswell:

```
== 2020-04-21 12:12:17,560 easyblock.py:2848 INFO Running method install_step part of step install
== 2020-04-21 12:16:38,233 build_log.py:164 ERROR EasyBuild crashed with an error (at easybuild/2019b/src/easybuild-framework/easybuild/base/exceptions.py:124 in __init__): run_cmd_qa: cmd ./StartTUI.sh : Max nohits 200 reached: end of output ucture
  fe-safe

do not search using EXALEAD
Enter selection (default: Install): Installation in progress...
Logs are located in "/rds/bear-apps/2019b/EL7-haswell/software/ABAQUS/2020/doc/InstallData/log/20200421T121220+0100_DOC_English_SIM_EstPrd.media"
```

BUT

The install log suggests that it all installed correctly, just EasyBuild was waiting for a Q/A that never came...

```
easyconfigs $ cat /rds/bear-apps/2019b/EL7-haswell/software/ABAQUS/2020/doc/InstallData/log/20200421T121220+0100_DOC_English_SIM_EstPrd.media/Everything.log
20200421T121220+0100| Startup infos
  Installer location: /dev/shm/build-edmondac-admin/edmondac-admin-2019b/ABAQUS/2020/system-system/AM_SIM_Abaqus_Extend.AllOS/5/SIMULIA_Documentation/AllOS/1/inst/linux_a64
  Media location: /dev/shm/build-edmondac-admin/edmondac-admin-2019b/ABAQUS/2020/system-system/AM_SIM_Abaqus_Extend.AllOS/5/SIMULIA_Documentation/AllOS/1
  Hostname: bber0501u03a.bb2.cluster
  UI is admin: no
  JS0GROUP build id: 20190930T180016Z
  OS infos: Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64
  UI mode: .TUI
20200421T121220+0100| Executing InstallTypeCheckAction DOC\English\SIM_EstPrd.media:DSYInstallTypeCheckAction
  Duration: 2ms
20200421T121220+0100| Executing RegInternalAction DOC\English\SIM_EstPrd.media:DSYRegInternalGet
  Duration: 0ms
20200421T121220+0100| Executing RegInternalAction DOC\English\SIM_EstPrd.media:DSYRegInternalCheckIdent
  Duration: 0ms
20200421T121221+0100| Installer mode: First install
20200421T121221+0100| Executing CheckFileAction DOC\English\SIM_EstPrd.media:DSYAdmInt_CM_check_file_action
CheckFileAction Path to check: /rds/bear-apps/2019b/EL7-haswell/software/ABAQUS/2020/doc Type: dir Check:existOrCreatable
Check File is true
  Duration: 0ms
20200421T121221+0100| Executing LockAction DOC\English\SIM_EstPrd.media:LockTargetPathAction
20200421T121221+0100| Create lock "/rds/bear-apps/2019b/EL7-haswell/software/ABAQUS/2020/doc" with hash DSYIns_0ddd6c476094bce9841b886fb1ec6204748d5b409d83253f0c45251c0fe49e46
Locking DSYIns_0ddd6c476094bce9841b886fb1ec6204748d5b409d83253f0c45251c0fe49e46
  Duration: 0ms
20200421T121225+0100| Resume panel
Files will be installed in the following directory:
  /rds/bear-apps/2019b/EL7-haswell/software/ABAQUS/2020/doc
Selected Components:
  Abaqus CAE
  Isight Desktop
  SIMULIA Execution Engine
  SIMULIA Execution Engine Station
  Tosca Fluid
  Tosca Structure
  fe-safe

do not search using EXALEAD
20200421T121225+0100| Executing CreateDirAction DOC\English\SIM_EstPrd.media:_CreateInstallDataDir
  Duration: 2ms
20200421T121225+0100| Executing CopyDirAction DOC\English\SIM_EstPrd.media:DSYAdmInt_CopyDirCATInstCommon
  Duration: 74ms
20200421T121225+0100| Executing CopyDirAction DOC\English\SIM_EstPrd.media:DSYAdmInt_CopyDirCATInst
  Duration: 53ms
20200421T121225+0100| Executing CopyDirAction DOC\English\SIM_EstPrd.media:DSYAdmInt_CopyDirSetup
  Duration: 2ms
20200421T121225+0100| Executing CopyDirAction DOC\English\SIM_EstPrd.media:DSYAdmInt_CopyDirTUI
  Duration: 1ms
20200421T121225+0100| Executing CopyDirAction DOC\English\SIM_EstPrd.media:DSYAdmInt_CopyDirSetupSh
  Duration: 1ms
20200421T121225+0100| Executing CopyDirAction DOC\English\SIM_EstPrd.media:DSYAdmInt_CopyDirTUISh
  Duration: 1ms
20200421T121225+0100| Executing CopyDirAction DOC\English\SIM_EstPrd.media:DSYAdmInt_CopyDirUninstall
  Duration: 0ms
20200421T121225+0100| Executing CopyDirAction DOC\English\SIM_EstPrd.media:DSYAdmInt_CopyDirUninstallSh
  Duration: 1ms
20200421T121225+0100| Executing RegInternalAction DOC\English\SIM_EstPrd.media:DSYRegInternalCreateAddRemove
  Duration: 0ms
20200421T121225+0100| Executing RegInternalAction DOC\English\SIM_EstPrd.media:DSYRegInternalAddAddRemove
  Duration: 0ms
20200421T121225+0100| Executing FileAction DOC\English\HPDoc_SIMULIA:
  Duration: 4ms
20200421T121225+0100| Executing FileAction DOC\English\SIMACAEDoc:
  Duration: 51s
20200421T121316+0100| Executing FileAction DOC\English\SIMACAEMedia:
  Duration: 13s
20200421T121330+0100| Executing FileAction DOC\English\SIMAINPDoc:
  Duration: 134s
20200421T121544+0100| Executing FileAction DOC\English\Frame:
  Duration: 762ms
20200421T121545+0100| Executing FileAction DOC\English\Graphics:
  Duration: 202s
20200421T121907+0100| Executing FileAction DOC\English\SIMA3DXMedia:
  Duration: 39s
20200421T121947+0100| Executing FileAction DOC\English\FrameSIMULIA_Established:
  Duration: 164ms
20200421T121947+0100| Executing FileAction DOC\English\MathJax:
  Duration: 1s
20200421T121948+0100| Executing FileAction DOC\English\SimEstiDoc:
  Duration: 552ms
20200421T121949+0100| Executing FileAction DOC\English\SimEstiMedia:
  Duration: 5ms
20200421T121949+0100| Executing FileAction DOC\English\IhrDoc:
  Duration: 13s
20200421T122002+0100| Executing FileAction DOC\English\IhrMedia:
  Duration: 2s
20200421T122005+0100| Executing FileAction DOC\English\X1eMedia:
  Duration: 211ms
20200421T122005+0100| Executing FileAction DOC\English\X1eDoc:
  Duration: 2s
20200421T122008+0100| Executing FileAction DOC\English\SimTsoDoc:
  Duration: 4s
20200421T122012+0100| Executing FileAction DOC\English\SimTsoMedia:
  Duration: 6s
20200421T122019+0100| Executing FileAction DOC\English\SimTfoDoc:
  Duration: 1s
20200421T122021+0100| Executing FileAction DOC\English\SimTfoMedia:
  Duration: 572ms
20200421T122021+0100| Executing FileAction DOC\English\SimFesafeDoc:
  Duration: 650ms
20200421T122022+0100| Executing FileAction DOC\English\SimFesafeMedia:
  Duration: 1s
20200421T122023+0100| Executing CreateShortcutAction DOC\English\SIM_EstPrd.media:DSYSoftwareMgtShortcut
  Duration: 0ms
20200421T122023+0100| Executing CreateShortcutAction DOC\English\SIM_EstPrd.media:DSYSoftwareMgtShortcut_createXML
  Duration: 0ms
20200421T122023+0100| Executing CreateShortcutAction DOC\English\SIM_EstPrd.media:makeShortcut_documentation_English
  Duration: 0ms
20200421T122023+0100| Executing RegInternalAction DOC\English\SIM_EstPrd.media:DSYRegInternalCreate
  Duration: 0ms
20200421T122023+0100| Executing LaunchAppAction DOC\English\InsV6Installation:doc_idx_done
  Traces number: 0001
  Duration: 2s
20200421T122026+0100| Executing LaunchAppAction DOC\English\InsV6Installation:multimedia_idx_done
  Traces number: 0002
  Duration: 1s
20200421T122027+0100| Executing LaunchAppAction DOC\English\InsV6Installation:list_done
  Traces number: 0003
  Duration: 1s
20200421T122028+0100| Executing LaunchAppAction DOC\English\InsV6Installation:pdf_idx_done
  Traces number: 0004
  Duration: 1s
20200421T122029+0100| Executing LaunchAppAction DOC\English\InsV6Installation:caa_idx_done
  Traces number: 0005
  Duration: 1s
20200421T122030+0100| Executing LaunchAppAction DOC\English\InsV6Installation:module_idx_done
  Traces number: 0006
  Duration: 1s
20200421T122031+0100| Executing LaunchAppAction DOC\English\InsV6Installation:gloss_idx_done
  Traces number: 0007
  Duration: 1s
20200421T122032+0100| Finish panel
  The installation program has finished installing SIMULIA 2020 Documentation on your computer, in /rds/bear-apps/2019b/EL7-haswell/software/ABAQUS/2020/doc.

  Installed Components:
    Abaqus CAE
    Isight Desktop
    SIMULIA Execution Engine
    SIMULIA Execution Engine Station
    Tosca Fluid
    Tosca Structure
    fe-safe

20200421T122032+0100| Statistics
  Installed CAFs: 21
  Begin Install:   2020-04-21T12:12:25+0100
  End Install:     2020-04-21T12:20:32+0100
  Close Installer: 2020-04-21T12:20:32+0100
```

**Comment by edmondac** [comment]
Failed on cascadelake:

```
== 2020-04-21 12:23:49,145 build_log.py:164 ERROR EasyBuild crashed with an error (at easybuild/2019b/src/easybuild-framework/easybuild/base/exceptions.py:124 in __init__): run_cmd_qa: cmd ./StartTUI.sh : Max nohits 200 reached: end of output 



________________________________________________________________________________

   SIMULIA Established Products 2020  
________________________________________________________________________________

Select Tosca Solver Interfaces ...
Input !b to get the previous page. Input !q and hit Enter to quit. Just press Enter to continue.

  1 (X) ABAQUS Interface
  2 ( ) MSC.NASTRAN Interface
  3 ( ) ANSYS Interface
  4 ( ) Femfat Interface
  5 ( ) ANSA Interface
Enter selection (default: Next):  (at easybuild/2019b/src/easybuild-framework/easybuild/tools/run.py:471 in run_cmd_qa)
== 2020-04-21 12:23:49,146 easyblock.py:3094 WARNING build failed (first 300 chars): run_cmd_qa: cmd ./StartTUI.sh : Max nohits 200 reached: end of output 



________________________________________________________________________________

   SIMULIA Established Products 2020  
________________________________________________________________________________

Select Tosca Solver Int
== 2020-04-21 12:23:49,146 easyblock.py:295 INFO Closing log for application name ABAQUS version 2020

```

**Comment by afraz-ahmed** [comment]
Both Haswell and cascadelake failures indicate that this line in abaqus.py didn't work as intended (although it does work _sometimes_):

`r"21 \[\*\] Abaqus/CFD Solver\n\nEnter selection \(default: Next\):": '7\n8\n\n',`

**Comment by afraz-ahmed** [comment]
Previously, I found this to be more reliable:
`"Abaqus/CFD Solver\n\nEnter selection \(default: Next\):": '0\n1\n2\n3\n4\n5\n6\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n\n\n',`

**Comment by edmondac** [comment]
Doesn't that risk answering subsequent questions with the wrong things?

**Comment by afraz-ahmed** [comment]
It seemed to work consistently when I tried it. I can test it out again.

**Pull request merged**
