### PR TITLE
GeoMxNGSPipeline

### PR DESCRIPTION
**Pull request by afraz-ahmed**
For INC1090579

`GeoMxNGSPipeline-2.0.eb`
* [x] Assigned to reviewer
* [ ] EL7-cascadelake
* [ ] EL7-haswell
* [ ] Ubuntu16 VM
* [ ] EL8-cascadelake
* [ ] EL8-haswell
* [ ] Ubuntu20 VM

### CODE REVIEW

**Review by edmondac — CHANGES_REQUESTED** [review]
Could you include a comment about the agreement that we're saying "yes" to?

**Comment by afraz-ahmed** [comment]
> Could you include a comment about the agreement that we're saying "yes" to?

I've sent the company an email, as every user might have to accept the agreement, in which case we can ask the user to install it himself.

Sorry - I should have read it properly the first time.

**Review by branfosj — APPROVED** [review]
👍

**Review by edmondac — APPROVED** [review]
lgtm

**Pull request merged**
