### PR TITLE
pytabix-0.1 easyconfig

### PR DESCRIPTION
**Pull request by afraz-ahmed**
For INC1015244

`pytabix-0.1-foss-2019b-Python-2.7.16.eb`
* [x] Assigned to reviewer
* [ ] EL7-cascadelake
* [ ] EL7-haswell
* [ ] EL7-sandybridge
* [ ] EL7-power9
* [ ] Ubuntu16 VM

### CODE REVIEW

**Comment by orbsmiv** [comment]
@afraz-ahmed as per @branfosj 's comments, this easyconf should technically use the PythonPackage easyblock due to it only containing a single package – however, we don't enforce this!

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/9c0a45e3da72a264427f958acc35dd95 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bber0501u03a.bb2.cluster - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/fa9b0b4ca82b313b1ab127753fe9b387 for a full test report.

**Comment by orbsmiv** [comment]
Built on all requested platforms

**Pull request merged**
